# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5.8/c2cciutils/schema.json

checks:
  codespell:
    ignore_re:
      - (.*/)?poetry\.lock
      - .github/changelog-generator-cache/.*

version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+)
      to: \1
    - from: master
      to: master
    - from: 7.6-20-04
      to: 7.6-20-04

publish:
  pypi:
    packages: []
  docker:
    dispatch: {}
    images:
      - name: camptocamp/mapserver
        tags:
          - '{version}'
          - '{version}-arm64'
